# Generated by Django 4.2.25 on 2025-10-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_assignment_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='name',
            field=models.CharField(default='Название задания', max_length=64),
            preserve_default=False,
        ),
    ]
