# Generated by Django 4.2.25 on 2025-10-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_assignment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='module',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
