site_name: Лабораторные работы по веб-разработке
site_description: Сайт с лабораторными работами

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.highlight
    - search.suggest
    
  palette:
    - scheme: default
      primary: amber
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - def_list
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details

nav:
  - Главная: ./main.md
  - Лабораторные работы:
    - Лабораторная 1: ./report_1.md
    - Лабораторная 2: ./report_2.md