# Generated by Django 4.2.25 on 2025-10-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_type', models.CharField(choices=[('student', 'Ученик'), ('teacher', 'Учитель'), ('admin', 'Администратор')], default='student', max_length=10)),
                ('username', models.CharField(db_index=True, max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
