# Generated by Django 6.0 on 2025-12-13 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=32, verbose_name='Марка')),
                ('model', models.CharField(max_length=32, verbose_name='Модель')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Информация об автомобиле',
                'verbose_name_plural': 'Информация об автомобилях',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='Полное имя')),
                ('passport', models.CharField(max_length=32, verbose_name='Паспортные данные')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(verbose_name='Количество мест')),
                ('engine_volume', models.FloatField(verbose_name='Объём двигателя')),
                ('fuel_type', models.IntegerField(choices=[(1, 'АИ-92'), (2, 'АИ-95'), (3, 'АИ-98'), (4, 'АИ-100'), (5, 'ДТ'), (6, 'Электрический'), (7, 'Гибрид')], verbose_name='Тип топлива')),
                ('transmission', models.CharField(choices=[('A', 'Автоматическая'), ('M', 'Механическая')], max_length=20, verbose_name='Тип КПП')),
                ('clearance', models.FloatField(verbose_name='Дорожный просвет')),
                ('trunk_volume', models.IntegerField(verbose_name='Объем багажника')),
                ('tank_volume', models.IntegerField(verbose_name='Объём топливного бака')),
                ('fuel_consumption', models.FloatField(verbose_name='Расход топлива')),
                ('car_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='core.carinfo')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='CarInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, verbose_name='Госномер')),
                ('vincode', models.CharField(max_length=50, verbose_name='VIN-код')),
                ('price', models.IntegerField(verbose_name='Цена проката')),
                ('color', models.CharField(max_length=32, verbose_name='Цвет')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='core.car')),
            ],
            options={
                'verbose_name': 'Экземпляр автомобиля',
                'verbose_name_plural': 'Экземпляры автомобилей',
            },
        ),
        migrations.CreateModel(
            name='CarCrash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата аварии')),
                ('damage', models.FloatField(verbose_name='Ущерб')),
                ('info', models.TextField(verbose_name='Информация об аварии')),
                ('car_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crashes', to='core.carinstance')),
            ],
            options={
                'verbose_name': 'Авария',
                'verbose_name_plural': 'Аварии',
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата штрафа')),
                ('cost', models.FloatField(verbose_name='Сумма штрафа')),
                ('description', models.TextField(verbose_name='Описание')),
                ('car_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='core.carinstance', verbose_name='Экземпляр автомобиля')),
            ],
            options={
                'verbose_name': 'Штраф',
                'verbose_name_plural': 'Штрафы',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='core.user')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
                ('position', models.CharField(max_length=64, verbose_name='Должность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='core.user')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='RentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала аренды')),
                ('return_date', models.DateTimeField(verbose_name='Планируемая дата возврата')),
                ('real_return_date', models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата возврата')),
                ('car_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.carinstance')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.client')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.worker')),
            ],
            options={
                'verbose_name': 'Договор аренды',
                'verbose_name_plural': 'Договоры аренды',
            },
        ),
    ]
