# Generated by Django 6.0 on 2025-12-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='gen',
            field=models.CharField(default='idk', max_length=32, verbose_name='Поколение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carinstance',
            name='year',
            field=models.IntegerField(default=2020, verbose_name='Год'),
            preserve_default=False,
        ),
    ]
