# Generated by Django 6.0 on 2025-12-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_car_gen_carinstance_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='horsepower',
            field=models.IntegerField(default=184, verbose_name='Мощность двигателя'),
            preserve_default=False,
        ),
    ]
